export const projects = [
  {
    id: 1,
    imgUrl: "/images/projects/desafio-newcon.png",
    title: "Teste de vaga Front-end (NewCon)",
    description: "SPA desenvolvida em React utilizando as boas práticas do DDD. Implementando operações CRUD e consumindo uma API construída em ASP.NET Core.",
    tags: ["Web"],
    githubUrl: "https://github.com/CaioSouzalimaa/teste-newcon",
    previewUrl: "",
  },
  {
    id: 2,
    imgUrl: "/images/projects/notion.png",
    title: "Notion Clone",
    description: "Clone do notion utilizando React, Typescript, Tailwindcss e tiptap editor.",
    tags: ["Web"],
    githubUrl: "https://github.com/CaioSouzalimaa/notion",
    previewUrl: "",
  },
  {
    id: 3,
    imgUrl: "/images/projects/capputeeno.png",
    title: "Teste de vaga Front-end (Rocketseat)",
    description: "E-commerce para venda de canecas e camisetas.",
    tags: ["Web"],
    githubUrl: "https://github.com/CaioSouzalimaa/desafio-de-vaga-front-end",
    previewUrl: "",
  },
  {
    id: 4,
    imgUrl: "/images/projects/nlw-return.png",
    title: "Widget de feedback sobre problemas ou dúvidas em seu site",
    description: "Widget que possibilita o usuário enviar feedback para o desenvolvedor sobre problemas ou dúvidas em seu site!",
    tags: ["Web"],
    githubUrl: "https://github.com/CaioSouzalimaa/NLW-RETURN",
    previewUrl: "https://nlw-return-chi-mauve.vercel.app/",
  },
  {
    id: 5,
    imgUrl: "/images/projects/attendance-list.png",
    title: "Lista de presença",
    description: "Lista de presença utilizando React.",
    tags: ["Web"],
    githubUrl: "https://github.com/CaioSouzalimaa/Attendance-List",
    previewUrl: "",
  },
  {
    id: 6,
    imgUrl: "/images/projects/gestures.png",
    title: "Reconhecimento de gestos",
    description: "Reconhecimento de gestos da mão usando JavaScript, TensorFlow e o pacote Fingerpose.",
    tags: ["Web"],
    githubUrl: "https://github.com/CaioSouzalimaa/gestures",
    previewUrl: "",
  },
  {
    id: 7,
    imgUrl: "/images/projects/controlar-por-gestos.png",
    title: "Site controlado por gestos",
    description: "Esse projeto consiste em controlarmos o site apenas com gestos e expressões faciais e tudo isso sem back-end.",
    tags: ["Web"],
    githubUrl: "https://github.com/CaioSouzalimaa/semana-javascript-expert07",
    previewUrl: "https://caiosouzalimaa.github.io/semana-javascript-expert07/initial-template/classes/pages/titles/",
  },
  {
    id: 8,
    imgUrl: "/images/projects/menu-navegacao.png",
    title: "Menu de navegação",
    description: "Menu de navegação animado.",
    tags: ["Web"],
    githubUrl: "https://github.com/CaioSouzalimaa/Menu-de-navegacao",
    previewUrl: "https://caiosouzalimaa.github.io/Menu-de-navegacao/",
  },
  {
    id: 9,
    imgUrl: "/images/projects/honey-comb-menu.png",
    title: "Menu estilo Favo de mel",
    description: "Menu estilo Favo de mel animado.",
    tags: ["Web"],
    githubUrl: "https://github.com/CaioSouzalimaa/HoneyCombMenu",
    previewUrl: "https://caiosouzalimaa.github.io/HoneyCombMenu/",
  },
  {
    id: 10,
    imgUrl: "/images/projects/balle-bot.png",
    title: "Landing-Page sobre um Bot de Discord",
    description: "Landing-Page destinada a informar o público sobre as utilidades do Balle Bot.",
    tags: ["Web"],
    githubUrl: "https://github.com/CaioSouzalimaa/Landing-Page",
    previewUrl: "https://caiosouzalimaa.github.io/Landing-Page/",
  },
  {
    id: 11,
    imgUrl: "/images/projects/calculadora.png",
    title: "Calculadora",
    description: "Calculadora funcional.",
    tags: ["Web"],
    githubUrl: "https://github.com/CaioSouzalimaa/calculator",
    previewUrl: "https://caiosouzalimaa.github.io/calculator/",
  }
];